[build]
  command = "pip install -r requirements.txt && npm ci && npm run build"
  publish = "dist"
  functions = "functions"

  [build.environment]
  RUST_VERSION = "stable"
  PYTHON_VERSION = "3.10"
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--prefer-offline --no-audit"

  [[plugins]]
  package = "@netlify/plugin-nextjs"

  [build.processing]
  skip_processing = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200