[build]
  command = "curl -sSf https://sh.rustup.rs | sh -s -- -y && . $HOME/.cargo/env && rustup default stable && pip install -r requirements.txt && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

