[build]
  command = "pip install -r requirements.txt && npm install --legacy-peer-deps --prefer-offline --no-audit --network-timeout=100000 && npm run build"
  publish = "dist"
  functions = "functions"

  [build.environment]
  RUST_VERSION = "stable"
  PYTHON_VERSION = "3.10"
  NODE_VERSION = "18.18.0"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_NETWORK_TIMEOUT = "100000"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
  NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "120000"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200